#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# Android dev build on a USB phone, for someone who has never set up Android
# tooling. macOS only. Run from anywhere: ./apps/mobile/scripts/android-setup.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_DIR="$(cd "$MOBILE_DIR/../.." && pwd)"
ENV_FILE="$MOBILE_DIR/.env.local"
SDK_DIR="$HOME/Library/Android/sdk"
JBR_DIR="/Applications/Android Studio.app/Contents/jbr/Contents/Home"
case "${SHELL:-}" in
  */bash) RC_FILE="$HOME/.bash_profile" ;;
  *) RC_FILE="$HOME/.zshrc" ;;
esac

TOTAL_STAGES=7

banner "Stride Android setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Check the basics"
if [[ "$(uname)" != "Darwin" ]]; then
  warn "This wizard is written for macOS. Steps may differ on $(uname)."
fi
if command -v node >/dev/null 2>&1; then
  say "Node $(node -v) found."
else
  warn "Node is missing. Install Node 20 or newer from https://nodejs.org, then re-run."
  exit 1
fi
if command -v pnpm >/dev/null 2>&1; then
  say "pnpm $(pnpm -v) found."
else
  warn "pnpm is missing. Run: corepack enable   (it ships with Node), then re-run."
  exit 1
fi
pause "Press Enter to continue."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Install Android Studio and the SDK"
if [[ -d "/Applications/Android Studio.app" ]]; then
  say "Android Studio is already installed."
else
  say "Android Studio brings the Android SDK, adb and a Java runtime in one install."
  open_url "https://developer.android.com/studio"
  step "Download Android Studio for Mac (pick Apple chip or Intel to match your Mac)."
  step "Open the .dmg and drag Android Studio into Applications."
fi
step "Open Android Studio. On first launch, choose Standard setup and accept every licence."
step "Let it finish downloading components. It installs the SDK to ~/Library/Android/sdk."
step "On the Welcome screen click More Actions → SDK Manager."
step "SDK Platforms tab: tick the newest Android version listed."
step "SDK Tools tab: tick Android SDK Build-Tools, Android SDK Command-line Tools,"
step "  and Android SDK Platform-Tools. Click Apply, then OK."
note "You never need to open a project in Android Studio. Close it when the downloads finish."
pause "Press Enter once the SDK Manager downloads are done."
if [[ -d "$SDK_DIR/platform-tools" ]]; then
  say "Found the SDK at $SDK_DIR."
else
  warn "No SDK at $SDK_DIR yet. If Android Studio used another folder, note it."
  warn "SDK Manager shows the path at the top as 'Android SDK Location'."
  ask CUSTOM_SDK "Paste the SDK location, or press Enter to keep $SDK_DIR:"
  [[ -n "${CUSTOM_SDK:-}" ]] && SDK_DIR="$CUSTOM_SDK"
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Point your shell at the SDK"
say "The build needs ANDROID_HOME, JAVA_HOME and adb on your PATH."
say "This adds a marked block to $RC_FILE:"
note "  export ANDROID_HOME=\"$SDK_DIR\""
note "  export JAVA_HOME=\"$JBR_DIR\""
note "  export PATH=\"\$ANDROID_HOME/platform-tools:\$ANDROID_HOME/emulator:\$PATH\""
if grep -q "# >>> stride android >>>" "$RC_FILE" 2>/dev/null; then
  say "The block is already in $RC_FILE. Leaving it alone."
elif confirm "Add it to $RC_FILE?"; then
  {
    printf '\n# >>> stride android >>>\n'
    printf 'export ANDROID_HOME="%s"\n' "$SDK_DIR"
    printf 'export JAVA_HOME="%s"\n' "$JBR_DIR"
    printf 'export PATH="$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH"\n'
    printf '# <<< stride android <<<\n'
  } >> "$RC_FILE"
  printf '  %s✓ updated%s %s\n' "$GREEN" "$RESET" "$RC_FILE"
else
  SKIPPED+=("Add ANDROID_HOME, JAVA_HOME and platform-tools to $RC_FILE")
fi
export ANDROID_HOME="$SDK_DIR"
export JAVA_HOME="$JBR_DIR"
export PATH="$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH"
note "New terminal windows pick this up. This wizard already uses it."
pause "Press Enter to continue."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Turn on USB debugging on the phone"
say "Menu names vary a little by brand. Use the phone's Settings search if lost."
step "Settings → About phone → tap 'Build number' 7 times. Enter your PIN if asked."
note "  On some phones Build number sits under About phone → Software information."
step "You'll see 'You are now a developer'."
step "Settings → System → Developer options → turn on 'USB debugging'."
step "Plug the phone into this Mac with a USB cable that carries data."
step "If the phone asks what the USB connection is for, choose 'File transfer'."
step "When 'Allow USB debugging?' pops up, tick 'Always allow from this computer' → Allow."
pause "Press Enter once the phone is plugged in and you tapped Allow."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Check that adb sees the phone"
if ! command -v adb >/dev/null 2>&1; then
  warn "adb is not on PATH. Check that $ANDROID_HOME/platform-tools exists (stage 2)."
  exit 1
fi
while true; do
  adb start-server >/dev/null 2>&1 || true
  DEVICES="$(adb devices | sed '1d' | grep -v '^$' || true)"
  printf '%s\n' "${DEVICES:-  (no devices)}" | sed 's/^/  /'
  if grep -q $'\tdevice$' <<<"$DEVICES"; then
    say "${GREEN}Phone connected.${RESET}"
    break
  elif grep -q 'unauthorized' <<<"$DEVICES"; then
    warn "The phone is connected but not trusted. Unlock it and tap Allow on the prompt."
  else
    warn "No phone found. Try another cable or USB port, and check USB debugging is on."
  fi
  confirm "Check again?" || { SKIPPED+=("Get 'adb devices' to list the phone as 'device'"); break; }
done
pause "Press Enter to continue."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "App keys"
say "The app needs two public values. Both are safe to ship in the app bundle."
say "They go in $ENV_FILE, which git ignores."
step "Clerk publishable key: same one the web app uses (VITE_CLERK_PUBLISHABLE_KEY)."
step "  Or: Clerk dashboard → your app → Configure → API keys → Publishable key (pk_...)."
open_url "https://dashboard.clerk.com"
ask EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY "Paste the Clerk publishable key:"
step "Convex URL: the CONVEX_URL line in packages/backend/.env.local (https://...convex.cloud)."
step "  Or: Convex dashboard → your deployment → Settings → URL & Deploy Key."
ask EXPO_PUBLIC_CONVEX_URL "Paste the Convex URL:"
if [[ -n "${EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY:-}" ]]; then
  write_env EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY "$EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY"
else
  SKIPPED+=("Set EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY in $ENV_FILE")
fi
if [[ -n "${EXPO_PUBLIC_CONVEX_URL:-}" ]]; then
  write_env EXPO_PUBLIC_CONVEX_URL "$EXPO_PUBLIC_CONVEX_URL"
else
  SKIPPED+=("Set EXPO_PUBLIC_CONVEX_URL in $ENV_FILE")
fi
pause "Press Enter to continue."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Build and install Stride on the phone"
say "This installs project packages, builds the Android dev app, and opens it on the phone."
note "The first build downloads Gradle and more SDK parts. Expect 5 to 15 minutes."
note "Keep the phone unlocked. If the phone asks to install the app, allow it."
if confirm "Start the build now?"; then
  (cd "$REPO_DIR" && pnpm install && pnpm --filter @stride/mobile android) || {
    warn "The build stopped. Read the last red lines above; they name the missing piece."
    SKIPPED+=("Finish the first build: pnpm --filter @stride/mobile android")
  }
else
  SKIPPED+=("Build the app: cd $REPO_DIR && pnpm --filter @stride/mobile android")
fi
note "After the first build, day to day you only need: pnpm dev:mobile"
note "Rebuild with the android command again only after native packages change."
pause "Press Enter to finish."

finish
