import { writeFileSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { colors, typography, spacing, radius, motion } from './tokens.ts'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '../../..')
const webStylesOut = resolve(root, 'apps/web/src/styles/tokens.generated.css')

const c = colors
const t = typography
const s = spacing
const r = radius
const m = motion

const css = `/* ============================================================
   DO NOT EDIT — generated by packages/shared/src/build-tokens.ts
   Run: pnpm build:tokens
   ============================================================ */

@theme {
  /* ---------- Brand (never flips) ---------- */
  --color-ink: ${c.brand.ink};
  --color-lavender: ${c.brand.lavender};
  --color-sky: ${c.brand.sky};
  --color-peach: ${c.brand.peach};
  --color-mint: ${c.brand.mint};
  --color-bubblegum: ${c.brand.bubblegum};
  --color-sunshine: ${c.brand.sunshine};
  --color-error: ${c.light.error};

  /* ---------- Soft accent fills ---------- */
  --color-lavender-soft: ${c.light.lavenderSoft};
  --color-sky-soft: ${c.light.skySoft};
  --color-peach-soft: ${c.light.peachSoft};
  --color-mint-soft: ${c.light.mintSoft};
  --color-bubblegum-soft: ${c.light.bubblegumSoft};

  /* ---------- Status ---------- */
  --color-success: ${c.light.success};
  --color-success-soft: ${c.light.successSoft};
  --color-streak: ${c.light.streak};

  /* ---------- Chat bubble ---------- */
  --color-bubble-user: ${c.light.bubbleUser};
  --color-bubble-user-text: ${c.light.bubbleUserText};

  /* ---------- Semantic surfaces ---------- */
  --color-bg: ${c.light.bg};
  --color-card: ${c.light.card};
  --color-card-elev: ${c.light.cardElev};
  --color-input: ${c.light.input};

  /* ---------- Semantic text ---------- */
  --color-text: ${c.light.text};
  --color-text-muted: ${c.light.textMuted};
  --color-text-subtle: ${c.light.textSubtle};
  --color-text-on-ink: ${c.light.textOnInk};
  --color-text-on-accent: ${c.light.textOnAccent};

  /* ---------- Semantic borders ---------- */
  --color-border: ${c.light.border};
  --color-border-strong: ${c.light.borderStrong};

  /* ---------- Typography ---------- */
  --font-sans: ${t.fontSans};

  --text-micro: ${t.scale.micro.size};
  --text-micro--line-height: ${t.scale.micro.lh};
  --text-caption: ${t.scale.caption.size};
  --text-caption--line-height: ${t.scale.caption.lh};
  --text-body: ${t.scale.body.size};
  --text-body--line-height: ${t.scale.body.lh};
  --text-h3: ${t.scale.h3.size};
  --text-h3--line-height: ${t.scale.h3.lh};
  --text-h2: ${t.scale.h2.size};
  --text-h2--line-height: ${t.scale.h2.lh};
  --text-h1: ${t.scale.h1.size};
  --text-h1--line-height: ${t.scale.h1.lh};
  --text-display: ${t.scale.display.size};
  --text-display--line-height: ${t.scale.display.lh};

  --weight-regular: ${t.weight.regular};
  --weight-medium: ${t.weight.medium};
  --weight-semibold: ${t.weight.semibold};
  --weight-bold: ${t.weight.bold};
  --weight-extrabold: ${t.weight.extrabold};

  --tracking-tight: ${t.tracking.tight};
  --tracking-normal: ${t.tracking.normal};
  --tracking-label: ${t.tracking.label};

  /* ---------- Spacing ---------- */
  --spacing-1: ${s[1]};
  --spacing-2: ${s[2]};
  --spacing-3: ${s[3]};
  --spacing-4: ${s[4]};
  --spacing-5: ${s[5]};
  --spacing-6: ${s[6]};
  --spacing-8: ${s[8]};
  --spacing-10: ${s[10]};

  /* ---------- Radius ---------- */
  --radius-sm: ${r.sm};
  --radius-md: ${r.md};
  --radius-lg: ${r.lg};
  --radius-xl: ${r.xl};
  --radius-full: ${r.full};

  /* ---------- Shadows ---------- */
  --shadow-soft: ${c.light.shadowSoft};
  --shadow-float: ${c.light.shadowFloat};
  --shadow-card-hover: ${c.light.shadowCardHover};
  --shadow-elev: ${c.light.shadowElev};

  /* ---------- Motion ---------- */
  --ease-out-soft: ${m.easeOutSoft};
  --dur-fast: ${m.durFast};
  --dur-base: ${m.durBase};
  --dur-slow: ${m.durSlow};

  /* ---------- Animations ---------- */
  --animate-shimmer: shimmer 1.6s linear infinite;

  @keyframes shimmer {
    from { background-position: -200% 0; }
    to   { background-position: 200% 0; }
  }
}

/* ============================================================
   Dark mode overrides
   ============================================================ */

.dark {
  --color-bg: ${c.dark.bg};
  --color-card: ${c.dark.card};
  --color-card-elev: ${c.dark.cardElev};
  --color-input: ${c.dark.input};

  --color-text: ${c.dark.text};
  --color-text-muted: ${c.dark.textMuted};
  --color-text-subtle: ${c.dark.textSubtle};
  --color-text-on-ink: ${c.dark.textOnInk};
  --color-text-on-accent: ${c.dark.textOnAccent};

  --color-border: ${c.dark.border};
  --color-border-strong: ${c.dark.borderStrong};

  --color-lavender-soft: ${c.dark.lavenderSoft};
  --color-sky-soft: ${c.dark.skySoft};
  --color-peach-soft: ${c.dark.peachSoft};
  --color-mint-soft: ${c.dark.mintSoft};
  --color-bubblegum-soft: ${c.dark.bubblegumSoft};

  --color-error: ${c.dark.error};
  --color-bubble-user: ${c.dark.bubbleUser};
  --color-bubble-user-text: ${c.dark.bubbleUserText};

  --shadow-soft: ${c.dark.shadowSoft};
  --shadow-float: ${c.dark.shadowFloat};
  --shadow-card-hover: ${c.dark.shadowCardHover};
  --shadow-elev: ${c.dark.shadowElev};
}
`

mkdirSync(resolve(root, 'apps/web/src/styles'), { recursive: true })
writeFileSync(webStylesOut, css, 'utf8')
console.log(`✓ tokens.generated.css → ${webStylesOut}`)
